version: "3"

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins_server
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"